#pragma once
#include "../Utilities/CommonUtilities/Input.h"
#include "ScriptGraph/Nodes/InputNode.h"

#define DECLARE_INPUT_NODE_FOR_KEY(KEY) \
DECLARE_GRAPH_NODE(SGNode_InputEvent_##KEY, ScriptGraphInputNode) \
{\
public:\
    SGNode_InputEvent_##KEY(); \
    FORCEINLINE std::string_view GetNodeTitle() const override { return #KEY"_Key"; } \
    FORCEINLINE std::string_view GetEntryHandle() const override { return #KEY"_Input"; } \
    FORCEINLINE ScriptGraphNodeType GetNodeType() const override { return ScriptGraphNodeType::Event; } \
};

#define IMPLEMENT_INPUT_NODE_FOR_KEY(KEY) \
IMPLEMENT_GRAPH_NODE(SGNode_InputEvent_##KEY, ScriptGraphInputNode) \
SGNode_InputEvent_##KEY::SGNode_InputEvent_##KEY() \
{ \
    myKey = static_cast<int>(CommonUtilities::Keys::KEY); \
}
//declare here and implement in cpp file
DECLARE_INPUT_NODE_FOR_KEY(A)
DECLARE_INPUT_NODE_FOR_KEY(B)
DECLARE_INPUT_NODE_FOR_KEY(C)
DECLARE_INPUT_NODE_FOR_KEY(D)
DECLARE_INPUT_NODE_FOR_KEY(E)
DECLARE_INPUT_NODE_FOR_KEY(F)
DECLARE_INPUT_NODE_FOR_KEY(G)
DECLARE_INPUT_NODE_FOR_KEY(H)
DECLARE_INPUT_NODE_FOR_KEY(I)
DECLARE_INPUT_NODE_FOR_KEY(J)
DECLARE_INPUT_NODE_FOR_KEY(K)
DECLARE_INPUT_NODE_FOR_KEY(L)
DECLARE_INPUT_NODE_FOR_KEY(M)
DECLARE_INPUT_NODE_FOR_KEY(N)
DECLARE_INPUT_NODE_FOR_KEY(O)
DECLARE_INPUT_NODE_FOR_KEY(P)
DECLARE_INPUT_NODE_FOR_KEY(Q)
DECLARE_INPUT_NODE_FOR_KEY(R)
DECLARE_INPUT_NODE_FOR_KEY(S)
DECLARE_INPUT_NODE_FOR_KEY(T)
DECLARE_INPUT_NODE_FOR_KEY(U)
DECLARE_INPUT_NODE_FOR_KEY(V)
DECLARE_INPUT_NODE_FOR_KEY(W)
DECLARE_INPUT_NODE_FOR_KEY(X)
DECLARE_INPUT_NODE_FOR_KEY(Y)
DECLARE_INPUT_NODE_FOR_KEY(Z)
DECLARE_INPUT_NODE_FOR_KEY(N1)
DECLARE_INPUT_NODE_FOR_KEY(N2)
DECLARE_INPUT_NODE_FOR_KEY(N3)
DECLARE_INPUT_NODE_FOR_KEY(N4)
DECLARE_INPUT_NODE_FOR_KEY(N5)
DECLARE_INPUT_NODE_FOR_KEY(N6)
DECLARE_INPUT_NODE_FOR_KEY(N7)
DECLARE_INPUT_NODE_FOR_KEY(N8)
DECLARE_INPUT_NODE_FOR_KEY(N9)
DECLARE_INPUT_NODE_FOR_KEY(N0)
DECLARE_INPUT_NODE_FOR_KEY(SPACE)
DECLARE_INPUT_NODE_FOR_KEY(RETURN)
DECLARE_INPUT_NODE_FOR_KEY(MOUSELBUTTON)
DECLARE_INPUT_NODE_FOR_KEY(MOUSERBUTTON)
DECLARE_INPUT_NODE_FOR_KEY(MOUSEMBUTTON)
